### PR TITLE
Add Linux support, fix a few compiler warnings, stop use of make_unique

### PR DESCRIPTION
**Pull request by Mrmayman**
I did a few things

- Linux support has been added to this project. This mainly includes adding Linux calls to the java File API. It now uses #ifdef and correctly picks the code based on the target OS.
- Removed use of make_unique as it was causing compiler errors (you can probably revert this if you like)
- Added a few more #include statements to remove warnings and errors

By the way, I'm kind of a newbie to C++ and git so forgive me for any stupid practices here. I messed up with the formatting so there's a lot of random changes related to that. I worked for 2 hours to get this to run on Linux.

### CODE REVIEW

**Comment by cuckydev** [comment]
I don't think I'll merge this because linux support should be done via a separate folder under java rather than putting ifdefs into the Win32 backend. Huge thanks for pointing out the issue with make_unique, I didn't realize it was C++14 (this project is configured to C++11 with no extensions), so I'll look into fixing that myself. I'll also try and get it building on linux myself later today.

**Comment by Mrmayman** [comment]
Alright, thanks for taking a look at this! Once you work on linux support the proper way, you can use parts of my committed code as a reference, if you want

**Comment by cuckydev** [comment]
I believe I now have it working on linux as of 65a554e5fea7f1650d341f9eb931df755dec29d5, though im having driver issues so i cant 100% confirm

**Comment by Mrmayman** [comment]
Yep it works. Nice!

**Pull request closed without merging**
